"""empty message

Revision ID: 096844ef610a
Revises: 
Create Date: 2022-04-14 14:28:41.934970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096844ef610a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_model')
    # ### end Alembic commands ###
